export const APP_CONFIG = {
  name: "SkillSwap",
  tagline: "Learn something. Teach something.",
  description: "The 1-on-1 peer skill exchange network powered by time credits.",
  welcomeCredits: 50,
  defaultCredits: 42,
  creditRatePerHour: 2, // 1 credit per 30 mins
} as const;

export const CREDIT_RULES = {
  welcomeBonus: 50,
  teachRewardPerSession: 10,
  learnCostPerSession: 10,
  sessionDurationMinutes: 30,
} as const;

export const DASHBOARD_NAV_ITEMS = [
  { id: "dashboard", label: "Dashboard", href: "/dashboard", iconName: "LayoutDashboard" },
  { id: "discover", label: "Discover", href: "/dashboard/discover", iconName: "Compass" },
  { id: "skills", label: "My Skills", href: "/dashboard/skills", iconName: "GraduationCap" },
  { id: "credits", label: "Wallet & Credits", href: "/dashboard/credits", iconName: "Coins" },
  { id: "sessions", label: "Sessions", href: "/dashboard/sessions", iconName: "Calendar" },
  { id: "messages", label: "Messages", href: "/dashboard/messages", iconName: "MessageSquare" },
  { id: "profile", label: "Profile", href: "/dashboard/profile", iconName: "User" },
  { id: "settings", label: "Settings", href: "/dashboard/settings", iconName: "Settings" },
] as const;

export const SKILL_CATEGORIES = [
  "All",
  "Code",
  "Design",
  "Business",
  "Language",
  "Music",
] as const;

export const DAYS_OF_WEEK = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
] as const;

export const TIME_SLOTS = [
  "Morning (9:00 AM – 12:00 PM)",
  "Afternoon (12:00 PM – 4:00 PM)",
  "Evening (4:00 PM – 8:00 PM)",
  "Night (8:00 PM – 11:00 PM)",
] as const;

export const SESSION_DURATIONS = [
  "30 minutes",
  "45 minutes",
  "60 minutes",
] as const;

export const LOCATIONS = [
  "Remote / Online (Global)",
  // Major Indian Cities
  "Chennai, India",
  "Bengaluru, India",
  "Mumbai, India",
  "Delhi NCR, India",
  "Hyderabad, India",
  "Pune, India",
  "Kolkata, India",
  "Ahmedabad, India",
  "Kochi, India",
  "Jaipur, India",
  "Chandigarh, India",
  "Coimbatore, India",
  "Indore, India",
  "Lucknow, India",
  "Surat, India",
  // North America
  "San Francisco Bay Area, USA",
  "New York City, USA",
  "Seattle, USA",
  "Austin, USA",
  "Boston, USA",
  "Los Angeles, USA",
  "Chicago, USA",
  "Denver, USA",
  "Atlanta, USA",
  "Washington D.C., USA",
  "San Diego, USA",
  "Dallas, USA",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Ottawa, Canada",
  "Calgary, Canada",
  "Waterloo, Canada",
  // Europe
  "London, UK",
  "Manchester, UK",
  "Edinburgh, UK",
  "Berlin, Germany",
  "Munich, Germany",
  "Frankfurt, Germany",
  "Paris, France",
  "Amsterdam, Netherlands",
  "Dublin, Ireland",
  "Zurich, Switzerland",
  "Stockholm, Sweden",
  "Copenhagen, Denmark",
  "Barcelona, Spain",
  "Madrid, Spain",
  "Rome, Italy",
  "Milan, Italy",
  "Vienna, Austria",
  "Warsaw, Poland",
  "Prague, Czech Republic",
  "Brussels, Belgium",
  "Lisbon, Portugal",
  "Helsinki, Finland",
  "Oslo, Norway",
  // Asia-Pacific & Australia
  "Singapore",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Seoul, South Korea",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Auckland, New Zealand",
  "Hong Kong",
  "Taipei, Taiwan",
  "Bangkok, Thailand",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Manila, Philippines",
  "Ho Chi Minh City, Vietnam",
  // Middle East & Africa
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Riyadh, Saudi Arabia",
  "Doha, Qatar",
  "Tel Aviv, Israel",
  "Cairo, Egypt",
  "Lagos, Nigeria",
  "Nairobi, Kenya",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  // Latin America
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Mexico City, Mexico",
  "Buenos Aires, Argentina",
  "Bogotá, Colombia",
  "Santiago, Chile",
  "Lima, Peru",
  // All Countries (A-Z)
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hong Kong SAR",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Maldives",
  "Malta",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Morocco",
  "Myanmar",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export const TIMEZONES = [
  "(UTC-11:00) Samoa, Midway Island (SST)",
  "(UTC-10:00) Hawaii Standard Time - Honolulu (HST)",
  "(UTC-09:00) Alaska Standard Time - Anchorage (AKST)",
  "(UTC-08:00) Pacific Time - Los Angeles, San Francisco, Vancouver (PST/PDT)",
  "(UTC-07:00) Mountain Time - Denver, Phoenix, Calgary (MST/MDT)",
  "(UTC-06:00) Central Time - Chicago, Dallas, Mexico City (CST/CDT)",
  "(UTC-05:00) Eastern Time - New York, Toronto, Miami, Bogota (EST/EDT)",
  "(UTC-04:00) Atlantic / Chile Time - Santiago, Halifax, Caracas (AST/CLT)",
  "(UTC-03:30) Newfoundland Time - St. John's (NST)",
  "(UTC-03:00) Argentina / Brazil Time - Buenos Aires, São Paulo (ART/BRT)",
  "(UTC-02:00) Mid-Atlantic Time - Fernando de Noronha",
  "(UTC-01:00) Azores, Cape Verde (AZOT/CVT)",
  "(UTC+00:00) Greenwich Mean Time - London, Dublin, Lisbon, Casablanca (GMT/UTC)",
  "(UTC+01:00) Central European Time - Berlin, Paris, Rome, Amsterdam, Lagos (CET)",
  "(UTC+02:00) Eastern European / Central Africa Time - Cairo, Johannesburg, Athens, Kyiv (EET/CAT)",
  "(UTC+03:00) Arabia / East Africa - Riyadh, Nairobi, Istanbul, Moscow (AST/EAT/MSK)",
  "(UTC+03:30) Iran Standard Time - Tehran (IRST)",
  "(UTC+04:00) Gulf Standard Time - Dubai, Abu Dhabi, Baku, Tbilisi (GST)",
  "(UTC+04:30) Afghanistan Time - Kabul (AFT)",
  "(UTC+05:00) Pakistan / West Asia - Karachi, Islamabad, Tashkent (PKT)",
  "(UTC+05:30) India Standard Time - Chennai, Bengaluru, Mumbai, Delhi, Sri Lanka (IST)",
  "(UTC+05:45) Nepal Time - Kathmandu (NPT)",
  "(UTC+06:00) Bangladesh Time - Dhaka, Almaty, Astana (BST)",
  "(UTC+06:30) Myanmar Time - Yangon (MMT)",
  "(UTC+07:00) Indochina Time - Bangkok, Jakarta, Hanoi, Ho Chi Minh (ICT/WIB)",
  "(UTC+08:00) Singapore, Hong Kong, Beijing, Perth, Kuala Lumpur, Manila (SGT/CST/AWST)",
  "(UTC+09:00) Japan & Korea Standard Time - Tokyo, Seoul, Osaka (JST/KST)",
  "(UTC+09:30) Australian Central Time - Adelaide, Darwin (ACST)",
  "(UTC+10:00) Australian Eastern Time - Sydney, Melbourne, Brisbane (AEST)",
  "(UTC+10:30) Lord Howe Standard Time (LHST)",
  "(UTC+11:00) Solomon Islands, Noumea (SBT)",
  "(UTC+12:00) New Zealand Standard Time - Auckland, Wellington, Fiji (NZST)",
  "(UTC+13:00) Tonga, Apia, Phoenix Islands (TOT)",
  "(UTC+14:00) Line Islands - Kiritimati (LINT)",
] as const;

export const DEFAULT_AVATARS = [
  "/avatars/avatar-1.svg",
  "/avatars/avatar-2.svg",
  "/avatars/avatar-3.svg",
  "/avatars/avatar-4.svg",
  "/avatars/avatar-5.svg",
  "/avatars/avatar-6.svg",
] as const;
