package com.skillswap.notification.entity;

public enum NotificationType {
    EXCHANGE_REQUEST_RECEIVED,
    EXCHANGE_REQUEST_ACCEPTED,
    EXCHANGE_REQUEST_REJECTED,
    SESSION_CREATED,
    SESSION_STARTED,
    SESSION_COMPLETED,
    NEW_MESSAGE,
    REVIEW_RECEIVED,
    DISPUTE_UPDATED,
    SAFETY_UPDATE,
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    SESSION_SCHEDULED,
    SESSION_RESCHEDULED,
    SESSION_REMINDER
}
